<#
.SYNOPSIS
    Generates k8s/base/secret.yaml from .env.secrets for Kubernetes deployment.

.DESCRIPTION
    Reads .env.secrets (git-ignored) in the project root and writes
    k8s/base/secret.yaml with the credential values required by the
    mlops-secrets Kubernetes Secret.

    Run once before the first "make k8s-up" on each developer machine.

.EXAMPLE
    .\scripts\k8s_setup_secret.ps1
    .\scripts\k8s_setup_secret.ps1 -EnvFile .env.local
#>

param(
    [string]$EnvFile   = ".env.secrets",
    [string]$OutputFile = "k8s\base\secret.yaml"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Resolve paths ─────────────────────────────────────────────────────────────
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$EnvPath     = Join-Path $ProjectRoot $EnvFile
$OutPath     = Join-Path $ProjectRoot $OutputFile

if (-not (Test-Path $EnvPath)) {
    Write-Error "[$EnvFile] not found at: $EnvPath`nCopy .env.example to .env.secrets and fill in real values."
    exit 1
}

# ── Parse .env file ───────────────────────────────────────────────────────────
$env_vars = @{}
foreach ($line in Get-Content $EnvPath) {
    $line = $line.Trim()
    if ($line -match '^\s*#' -or $line -eq '') { continue }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { continue }
    $key   = $line.Substring(0, $idx).Trim()
    $value = $line.Substring($idx + 1).Trim().Trim('"').Trim("'")
    $env_vars[$key] = $value
}

# ── Helper to fetch a key with a sensible fallback ────────────────────────────
function Get-Env {
    param([string]$Key, [string]$Default = "")
    if ($env_vars.ContainsKey($Key)) { return $env_vars[$Key] }
    return $Default
}

# ── Map .env.secrets keys → Kubernetes Secret keys ───────────────────────────
$db_password          = Get-Env "DB_PASSWORD"         "CHANGE_ME"
$airflow_password     = Get-Env "AIRFLOW_PASSWORD"     "CHANGE_ME"
$airflow_fernet_key   = Get-Env "AIRFLOW_FERNET_KEY"   ""
$airflow_secret_key   = Get-Env "AIRFLOW_SECRET_KEY"   ""
$grafana_password     = Get-Env "GRAFANA_PASSWORD"     "CHANGE_ME"
$api_secret_key       = Get-Env "API_SECRET_KEY"       "CHANGE_ME_min_32_chars_xyzabcdefgh"
$mlflow_user          = Get-Env "DAGSHUB_USER"         ""
$mlflow_password      = Get-Env "DAGSHUB_TOKEN"        ""
$github_token         = Get-Env "GITHUB_TOKEN"         ""

# ── Validate mandatory fields ─────────────────────────────────────────────────
$missing = @()
if ($db_password -eq "CHANGE_ME")           { $missing += "DB_PASSWORD" }
if ($api_secret_key -eq "CHANGE_ME_min_32_chars_xyzabcdefgh") { $missing += "API_SECRET_KEY" }

if ($missing.Count -gt 0) {
    Write-Warning "The following keys are missing / placeholder in $EnvFile`:"
    $missing | ForEach-Object { Write-Warning "  - $_" }
    Write-Warning "Proceeding with placeholder values — update $OutputFile before deploying."
}

# ── Write secret.yaml ─────────────────────────────────────────────────────────
$yaml = @"
# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by scripts/k8s_setup_secret.ps1
# DO NOT COMMIT — this file is git-ignored.
# Re-generate with: make k8s-secret
# Source: $EnvFile
# ────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  DB_PASSWORD: "$db_password"
  AIRFLOW_PASSWORD: "$airflow_password"
  AIRFLOW_FERNET_KEY: "$airflow_fernet_key"
  AIRFLOW_SECRET_KEY: "$airflow_secret_key"
  GF_SECURITY_ADMIN_PASSWORD: "$grafana_password"
  API_SECRET_KEY: "$api_secret_key"
  MLFLOW_TRACKING_USERNAME: "$mlflow_user"
  MLFLOW_TRACKING_PASSWORD: "$mlflow_password"
  GITHUB_TOKEN: "$github_token"
"@

# Ensure output directory exists
$OutDir = Split-Path -Parent $OutPath
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }

$yaml | Set-Content -Encoding UTF8 -Path $OutPath
Write-Host "[OK] Written: $OutputFile" -ForegroundColor Green
Write-Host "     Apply with: kubectl apply -f $OutputFile"
Write-Host "     Or just run: make k8s-up  (picks it up automatically)"
