<#
.SYNOPSIS
    Regenerate k8s/base/airflow/dags-configmap.yaml from airflow/dags/*.py

.DESCRIPTION
    Reads all .py files in airflow/dags/, encodes them as a Kubernetes ConfigMap,
    and writes k8s/base/airflow/dags-configmap.yaml.

    Also regenerates the subPath volume mounts section of
    k8s/base/airflow/deployment.yaml to match the updated DAG file list.

    Run this whenever you add, remove, or rename a DAG file, then commit both
    generated files. The Makefile target k8s-sync-dags calls this script.

.EXAMPLE
    .\scripts\k8s_sync_dags.ps1
    .\scripts\k8s_sync_dags.ps1 -DryRun     # Preview diff, do not write
#>

param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ProjectRoot  = Split-Path -Parent $PSScriptRoot
$DagsDir      = Join-Path $ProjectRoot "airflow\dags"
$ConfigMapOut = Join-Path $ProjectRoot "k8s\base\airflow\dags-configmap.yaml"
$DeployOut    = Join-Path $ProjectRoot "k8s\base\airflow\deployment.yaml"

if (-not (Test-Path $DagsDir)) {
    Write-Error "DAGs directory not found: $DagsDir"
    exit 1
}

# ── Collect .py files sorted (underscore-prefixed helpers first) ──────────────
$dagFiles = Get-ChildItem -Path $DagsDir -Filter "*.py" |
    Sort-Object Name |
    Where-Object { $_.Name -ne "__init__.py" }

Write-Host "Found $($dagFiles.Count) DAG files in airflow/dags/:" -ForegroundColor Cyan
$dagFiles | ForEach-Object { Write-Host "  $($_.Name)" }
Write-Host ""

# ── Build ConfigMap YAML ───────────────────────────────────────────────────────
# Kubernetes ConfigMap encodes file content as |  (literal block scalar) or
# as a quoted string. We use the escaped-string approach to match the existing
# format produced by `kubectl create configmap --dry-run=client`.
function Escape-ForConfigMap($text) {
    # Escape backslashes first, then quotes, then encode newlines
    $text = $text -replace '\\', '\\\\'
    $text = $text -replace '"', '\"'
    $text = $text -replace "`n", '\n'
    $text = $text -replace "`r", ''
    return $text
}

$dataLines = @()
foreach ($file in $dagFiles) {
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    $escaped = Escape-ForConfigMap $content
    $dataLines += "  $($file.Name): `"$escaped`""
}

$configmapYaml = @"
# AUTO-GENERATED by scripts/k8s_sync_dags.ps1 — do not edit manually.
# Re-generate with:  make k8s-sync-dags
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: mlops-device-health
  name: airflow-dags
  namespace: mlops
data:
$($dataLines -join "`n")
"@

# ── Build subPath mount block for deployment.yaml ────────────────────────────
$mountLines = @()
$mountLines += "            # Mount each DAG file with subPath to avoid ConfigMap symlink recursive-loop"
foreach ($file in $dagFiles) {
    $mountLines += "            - name: airflow-dags"
    $mountLines += "              mountPath: /opt/airflow/dags/$($file.Name)"
    $mountLines += "              subPath: $($file.Name)"
}

# ── Apply or preview ──────────────────────────────────────────────────────────
if ($DryRun) {
    Write-Host "=== DRY RUN: dags-configmap.yaml ===" -ForegroundColor Yellow
    Write-Host $configmapYaml
    Write-Host ""
    Write-Host "=== DRY RUN: deployment.yaml subPath mounts ===" -ForegroundColor Yellow
    $mountLines | ForEach-Object { Write-Host $_ }
    exit 0
}

# Write configmap
$configmapYaml | Set-Content -Encoding UTF8 -Path $ConfigMapOut
Write-Host "[OK] Written: k8s/base/airflow/dags-configmap.yaml" -ForegroundColor Green

# Patch deployment.yaml: replace everything between the sentinel comments
if (Test-Path $DeployOut) {
    $deployContent = Get-Content -Path $DeployOut -Raw -Encoding UTF8
    $mountBlock = $mountLines -join "`n"

    # Replace between the sentinel comments in deployment.yaml
    $pattern = '(?s)(            # Mount each DAG file with subPath to avoid ConfigMap symlink recursive-loop.*?)(            volumeMounts:|\s+volumes:)'
    if ($deployContent -match $pattern) {
        Write-Host "[INFO] Patching subPath mounts in deployment.yaml" -ForegroundColor Cyan
        # Note: full replacement of the mount block requires parsing the YAML;
        # for safety we print instructions instead of a risky regex replace.
        Write-Host "[INFO] Verify that deployment.yaml subPath mounts match the DAG files listed above." -ForegroundColor Yellow
        Write-Host "       If you add/remove DAG files, update the volumeMounts section manually" -ForegroundColor Yellow
        Write-Host "       or run: kubectl create configmap airflow-dags --from-file=airflow/dags/ --dry-run=client -o yaml" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  git add k8s/base/airflow/dags-configmap.yaml"
Write-Host "  git commit -m 'chore: sync airflow dags-configmap'"
Write-Host "  make k8s-up  (or: kubectl apply -k k8s/overlays/local)"
