#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# k8s_setup_secret.sh  — generate k8s/base/secret.yaml from .env.secrets
#
# Usage:
#   bash scripts/k8s_setup_secret.sh
#   ENV_FILE=.env.local bash scripts/k8s_setup_secret.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ENV_FILE="${ENV_FILE:-.env.secrets}"
OUTPUT_FILE="k8s/base/secret.yaml"

ENV_PATH="$PROJECT_ROOT/$ENV_FILE"
OUT_PATH="$PROJECT_ROOT/$OUTPUT_FILE"

if [[ ! -f "$ENV_PATH" ]]; then
    echo "ERROR: $ENV_FILE not found at $ENV_PATH"
    echo "       Copy .env.example to .env.secrets and fill in real values."
    exit 1
fi

# ── Parse .env file ───────────────────────────────────────────────────────────
get_env() {
    local key="$1"
    local default="${2:-}"
    local val
    val=$(grep -E "^${key}=" "$ENV_PATH" 2>/dev/null | tail -1 | cut -d'=' -f2- | sed "s/^['\"]//; s/['\"]$//")
    echo "${val:-$default}"
}

DB_PASSWORD=$(get_env DB_PASSWORD CHANGE_ME)
AIRFLOW_PASSWORD=$(get_env AIRFLOW_PASSWORD CHANGE_ME)
AIRFLOW_FERNET_KEY=$(get_env AIRFLOW_FERNET_KEY "")
AIRFLOW_SECRET_KEY=$(get_env AIRFLOW_SECRET_KEY "")
GRAFANA_PASSWORD=$(get_env GRAFANA_PASSWORD CHANGE_ME)
API_SECRET_KEY=$(get_env API_SECRET_KEY CHANGE_ME_min_32_chars)
MLFLOW_USER=$(get_env DAGSHUB_USER "")
MLFLOW_PASSWORD=$(get_env DAGSHUB_TOKEN "")
GITHUB_TOKEN=$(get_env GITHUB_TOKEN "")

mkdir -p "$(dirname "$OUT_PATH")"

cat > "$OUT_PATH" <<EOF
# ────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by scripts/k8s_setup_secret.sh
# DO NOT COMMIT — this file is git-ignored.
# Re-generate with: make k8s-secret
# Source: $ENV_FILE
# ────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  DB_PASSWORD: "$DB_PASSWORD"
  AIRFLOW_PASSWORD: "$AIRFLOW_PASSWORD"
  AIRFLOW_FERNET_KEY: "$AIRFLOW_FERNET_KEY"
  AIRFLOW_SECRET_KEY: "$AIRFLOW_SECRET_KEY"
  GF_SECURITY_ADMIN_PASSWORD: "$GRAFANA_PASSWORD"
  API_SECRET_KEY: "$API_SECRET_KEY"
  MLFLOW_TRACKING_USERNAME: "$MLFLOW_USER"
  MLFLOW_TRACKING_PASSWORD: "$MLFLOW_PASSWORD"
  GITHUB_TOKEN: "$GITHUB_TOKEN"
EOF

echo "[OK] Written: $OUTPUT_FILE"
echo "     Apply with: kubectl apply -f $OUTPUT_FILE"
echo "     Or just run: make k8s-up  (picks it up automatically)"
